name: Build and release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      WITNESS_DIST_DIR: ${{ github.workspace }}/.witness/dist
    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Witnessed build
        run: |
          mkdir -p "$WITNESS_DIST_DIR"
          ./witnessed-build -i

      - name: Manually tag
        run: echo "RELEASE_TAG=release-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.RELEASE_TAG }}
          generate_release_notes: true
          files: |
            .witness/dist/*
